# --- Этап 1: Сборка Vite проекта ---
FROM node:20-alpine AS builder
WORKDIR /app

# Копируем файлы зависимостей и устанавливаем их
COPY package*.json ./
RUN npm ci

# Копируем исходный код и собираем продакшн-версию
COPY . .
RUN npm run build

# --- Этап 2: Финальный контейнер с Nginx ---
FROM nginx:alpine

# Удаляем дефолтные файлы Nginx
RUN rm -rf /usr/share/nginx/html/*

# Копируем собранную статику из предыдущего этапа (builder) в папку Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем наш кастомный конфиг Nginx в контейнер
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
