/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as ClientsCarsRouteImport } from './routes/clients-cars'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoxesIndexRouteImport } from './routes/boxes/index'
import { Route as BoxesBoxIdRouteImport } from './routes/boxes/$boxId'

const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsCarsRoute = ClientsCarsRouteImport.update({
  id: '/clients-cars',
  path: '/clients-cars',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesIndexRoute = BoxesIndexRouteImport.update({
  id: '/boxes/',
  path: '/boxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBoxIdRoute = BoxesBoxIdRouteImport.update({
  id: '/boxes/$boxId',
  path: '/boxes/$boxId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/clients-cars': typeof ClientsCarsRoute
  '/prices': typeof PricesRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/boxes/': typeof BoxesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/clients-cars': typeof ClientsCarsRoute
  '/prices': typeof PricesRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/boxes': typeof BoxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/clients-cars': typeof ClientsCarsRoute
  '/prices': typeof PricesRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/boxes/': typeof BoxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/clients-cars'
    | '/prices'
    | '/boxes/$boxId'
    | '/boxes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brands' | '/clients-cars' | '/prices' | '/boxes/$boxId' | '/boxes'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/clients-cars'
    | '/prices'
    | '/boxes/$boxId'
    | '/boxes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  ClientsCarsRoute: typeof ClientsCarsRoute
  PricesRoute: typeof PricesRoute
  BoxesBoxIdRoute: typeof BoxesBoxIdRoute
  BoxesIndexRoute: typeof BoxesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients-cars': {
      id: '/clients-cars'
      path: '/clients-cars'
      fullPath: '/clients-cars'
      preLoaderRoute: typeof ClientsCarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/': {
      id: '/boxes/'
      path: '/boxes'
      fullPath: '/boxes/'
      preLoaderRoute: typeof BoxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$boxId': {
      id: '/boxes/$boxId'
      path: '/boxes/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof BoxesBoxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  ClientsCarsRoute: ClientsCarsRoute,
  PricesRoute: PricesRoute,
  BoxesBoxIdRoute: BoxesBoxIdRoute,
  BoxesIndexRoute: BoxesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
